import React, { useState } from 'react';
import { ModuleLayout } from '../../../components/ModuleLayout';
import { Card, Callout, Button } from '../../../components/ui';
import { BrainCircuit, Search, PenTool, AlertTriangle, CheckCircle2, XCircle } from 'lucide-react';

export default function Page() {
  const [quizAnswer, setQuizAnswer] = useState<string | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);

  const sections = [
    { id: 'what-is-it', title: 'What is Generative AI?' },
    { id: 'prediction', title: 'Prediction Engine' },
    { id: 'hallucinations', title: 'The Trust Gap' },
    { id: 'strengths', title: 'When to Use It' },
    { id: 'quiz', title: 'Knowledge Check' },
  ];

  return (
    <ModuleLayout
      title="AI Fundamentals"
      description="Look under the hood. Understand how Large Language Models (LLMs) actually work, so you know when to trust them—and when to doubt them."
      duration="15 mins"
      audience="All Employees"
      sections={sections}
      nextModulePath="/modules/prompting"
    >
      {/* SECTION 1: WHAT IS IT */}
      <section id="what-is-it" className="mb-12">
        <h2>It's Not a Search Engine</h2>
        <p>
          Most of us are used to Google. When you search for a document on the intranet, the computer looks for an exact match.
        </p>
        <p>
          <strong>Generative AI (like Gemini or ChatGPT) is different.</strong> It doesn't "look up" answers in a database. It <em>creates</em> new answers from scratch based on patterns it learned during training.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 not-prose my-6">
          <Card className="p-4 border-l-4 border-l-blue-500">
            <div className="flex items-center gap-2 mb-2 font-bold text-blue-900">
              <Search className="w-5 h-5" /> Search Engine
            </div>
            <p className="text-sm text-slate-600">Retrieves existing information.</p>
            <p className="text-xs text-slate-500 mt-2">"Find the 2024 Holiday Calendar PDF."</p>
          </Card>
          <Card className="p-4 border-l-4 border-l-purple-500">
            <div className="flex items-center gap-2 mb-2 font-bold text-purple-900">
              <BrainCircuit className="w-5 h-5" /> Generative AI
            </div>
            <p className="text-sm text-slate-600">Generates new content based on patterns.</p>
            <p className="text-xs text-slate-500 mt-2">"Draft an email announcing the 2024 holidays."</p>
          </Card>
        </div>
      </section>

      {/* SECTION 2: PREDICTION ENGINE */}
      <section id="prediction" className="mb-12">
        <h2>The "Autocomplete" Analogy</h2>
        <p>
          Think of LLMs as "Autocomplete on Steroids." They are trained on billions of sentences to predict the most likely next word.
        </p>
        <p>
          If you type: <em>"The quick brown fox jumps over the..."</em>
        </p>
        <p>
          The AI predicts <strong>"lazy dog"</strong> (99% probability).
        </p>
        <p>
          This means the AI doesn't always know facts. It knows <em>patterns</em>. This is why it can write poetry, code, and emails, but it can also make mistakes with math or obscure facts.
        </p>
      </section>

      {/* SECTION 3: HALLUCINATIONS */}
      <section id="hallucinations" className="mb-12">
        <h2>The Trust Gap: Hallucinations</h2>
        <p>
          Because the AI is trying to predict the "next likely word," it sometimes prioritizes <strong>fluency</strong> over <strong>accuracy</strong>.
        </p>
        <Callout variant="warning" title="What is a Hallucination?">
          A confident but completely false answer generated by AI.
        </Callout>
        
        <div className="my-6 not-prose">
          <h3 className="font-bold text-slate-900 mb-3">Real World Example:</h3>
          <Card className="p-6 bg-slate-50">
            <p className="font-mono text-sm text-slate-600 mb-2"><strong>User:</strong> "Summarize the 'Project Apollo' strategic report from 2019."</p>
            <p className="font-mono text-sm text-slate-800 mb-2"><strong>AI:</strong> "Project Apollo was a strategic initiative launched in Q3 2019 to optimize cloud infrastructure..."</p>
            <div className="flex items-center gap-2 text-red-600 text-sm font-bold mt-4">
              <AlertTriangle className="w-4 h-4" /> 
              Reality Check: We never had a "Project Apollo". The AI made it up because it sounded plausible.
            </div>
          </Card>
        </div>
      </section>

      {/* SECTION 4: STRENGTHS */}
      <section id="strengths" className="mb-12">
        <h2>Use the "Jagged Frontier"</h2>
        <p>
          AI is a genius at some things and a novice at others. Use it for its strengths, not its weaknesses.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 not-prose">
          <div className="bg-green-50 p-6 rounded-xl border border-green-100">
             <h3 className="font-bold text-green-800 flex items-center gap-2 mb-4">
               <CheckCircle2 className="w-5 h-5" /> The Sweet Spot
             </h3>
             <ul className="space-y-3 text-sm text-slate-700">
               <li><strong>Transformation:</strong> "Turn this bulleted list into an email."</li>
               <li><strong>Summarization:</strong> "Summarize this meeting transcript."</li>
               <li><strong>Ideation:</strong> "Give me 10 ideas for a team building event."</li>
               <li><strong>Drafting:</strong> "Write a first draft of a project plan."</li>
             </ul>
          </div>

          <div className="bg-red-50 p-6 rounded-xl border border-red-100">
             <h3 className="font-bold text-red-800 flex items-center gap-2 mb-4">
               <XCircle className="w-5 h-5" /> The Danger Zone
             </h3>
             <ul className="space-y-3 text-sm text-slate-700">
               <li><strong>Fact Retrieval:</strong> "What is our Q3 revenue?" (Use a database instead).</li>
               <li><strong>Math:</strong> "Calculate the ROI of these 50 rows." (Use Excel).</li>
               <li><strong>High Stakes:</strong> "Should we fire this employee?" (Use Human Judgment).</li>
             </ul>
          </div>
        </div>
      </section>

      {/* SECTION 5: QUIZ */}
      <section id="quiz" className="mb-12 pt-8 border-t border-slate-200">
        <h2>Knowledge Check</h2>
        <p className="mb-6">Which task is best suited for Generative AI?</p>

        <Card className="p-6 bg-slate-50 not-prose">
          <div className="grid grid-cols-1 gap-4">
            <button
              onClick={() => { setQuizAnswer('math'); setShowExplanation(true); }}
              className={`text-left p-4 rounded border-2 transition-all ${
                quizAnswer === 'math' 
                  ? 'border-red-500 bg-red-50' 
                  : 'border-slate-200 bg-white hover:border-blue-300'
              }`}
            >
              <span className="font-bold block mb-1">A. Calculate the exact variance of our yearly budget.</span>
            </button>

            <button
              onClick={() => { setQuizAnswer('summary'); setShowExplanation(true); }}
              className={`text-left p-4 rounded border-2 transition-all ${
                quizAnswer === 'summary' 
                  ? 'border-green-500 bg-green-50' 
                  : 'border-slate-200 bg-white hover:border-blue-300'
              }`}
            >
              <span className="font-bold block mb-1">B. Summarize a 10-page project proposal into key risks.</span>
            </button>
            
            <button
              onClick={() => { setQuizAnswer('search'); setShowExplanation(true); }}
              className={`text-left p-4 rounded border-2 transition-all ${
                quizAnswer === 'search' 
                  ? 'border-red-500 bg-red-50' 
                  : 'border-slate-200 bg-white hover:border-blue-300'
              }`}
            >
              <span className="font-bold block mb-1">C. Find the phone number for Client X.</span>
            </button>
          </div>

          {showExplanation && (
            <div className="mt-6 animate-fade-in">
              {quizAnswer === 'summary' ? (
                <div className="bg-green-100 text-green-800 p-4 rounded-lg">
                  <p className="font-bold">Correct!</p>
                  <p className="text-sm mt-1">
                    Summarization is a core strength of LLMs. They are great at distilling text. Math and Fact Retrieval are better suited for Calculators and Databases.
                  </p>
                </div>
              ) : (
                <div className="bg-red-100 text-red-800 p-4 rounded-lg">
                  <p className="font-bold">Not quite.</p>
                  <p className="text-sm mt-1">
                    AI can make mistakes with math and specific facts/phone numbers. It is safest when working with text you provide, like summarizing a document.
                  </p>
                </div>
              )}
            </div>
          )}
        </Card>
      </section>
    </ModuleLayout>
  );
}